### ISSUE TITLE
Issues with Callbacks

### ISSUE THREAD

**Issue by chrisly42** [vsilaev/tascalate-concurrent#10] opened 2018-08-06 06:57 UTC
Hi there,

me again. I have some issues with the callback mechanism used internally in tascalate-concurrent to add the successCallback etc.
The problems are due to the callbacks being added as another task execution via execute() on the Executor used.

I have identified two issues:

- If I shutdown() the executor, the remaining callback hooks will cause rejections on CallbackRegistry:291 executor.execute() and throw these exceptions all the way up, once a (previously executing) Promise completes.
- The extra task will cause starvation on SingleThreadExecutors. E.g. if I add several (hundreds) promises to the executor at once, the first promise will not terminate becauses the callback hook is only executed AFTER all other queued promises have been ALSO executed, due to in-order-execution.

Do you have any suggestions on this? Otherwise I probably have to revert to mutex/semaphores outside the executor to guarantee a single-threaded funnel, but that would defeat the purpose of the executor and might unnecessarily queue up threads waiting for the mutex to become available.

Thanks and keep up the good work
Chris

**Comment by chrisly42** [comment] 2018-08-21 06:43
Check this test case for part 1 of the problem:
```
@Test
    public void test_shutting_down_executor_will_not_hang_promise_due_to_pending_callback() throws ExecutionException, InterruptedException {
        TaskExecutorService singleThreadExecutor = TaskExecutors.newSingleThreadExecutor(new ThreadFactoryBuilder()
                .setDaemon(true)
                .setNameFormat("Bla-%d")
                .build());

        CountDownLatch latch = new CountDownLatch(1);
        AtomicBoolean flag = new AtomicBoolean();
        Promise<Void> p = CompletableTask.asyncOn(executor)
                .thenApplyAsync(v -> {
                    try {
                        latch.await();
                    } catch (InterruptedException ex) {
                    }
                    return v;
                }, singleThreadExecutor)
                .handleAsync((v, t) -> {
                    flag.set(true);
                    return null;
                });

        singleThreadExecutor.shutdown();
        latch.countDown();
        //singleThreadExecutor.awaitTermination(10, TimeUnit.SECONDS);
        p.get();
        assertTrue(flag.get());
    }
```
Above, p.get() will not terminate due to an rejection exception being thrown inside the promise.
The second part is probably just due to me having used .handle() instead of .handleAsync() with the old executor. I had assumed that specifying an executor in an async method will not overwrite the default executor specified before.

**Comment by chrisly42** [comment] 2018-08-21 06:56
Oh, another note: For the second part, I assumed that CompletableTask.asyncOn(executor) would behave the same as .defaultAsyncOn(executor), but it doesn't.

**Comment by vsilaev** [comment] 2018-08-21 08:00
This is by design:
```java
Promise<Void> p1 = CompletableTask.asyncOn(firstExecutor);
Promise<Void> p2 = p1.thenApplyAsync(..., secondExecutor);
```
`p1` will use `firstExecutor` for any async operations that do not specify explicit executor;
`p2` will use `secondExecutor` for any async operations that do not specify explicit executor;

Every operation returns a new promise, and it will either inherit defaultExecutor of originating promise (if no explicit executor is specified for operation) or will use explicitly supplied executor as default.

`Promise.defaultAsyncOn` is designed explicitly to alter this default behavior -- it returns a `Promise` wrapper with re-bound defaultExecutor.

In `net.tascalate.concurrent.AbstractCompletableTask` line 427+ :
```java
    private <U> AbstractCompletableTask<U> internalCreateCompletionStage(Executor executor) {
        // Preserve default async executor, or use user-supplied executor as default
        // But don't let SAME_THREAD_EXECUTOR to be a default async executor
        return createCompletionStage(executor == SAME_THREAD_EXECUTOR ? getDefaultExecutor() : executor);
    }
```
Here is `executor` param passed to method is what you supply via `thenApply(..., executor)`

So, again, this is by design and not a bug.

**Comment by vsilaev** [comment] 2018-08-21 08:08
To clarify the logic behinds this design. Imaging, you are reading source:
```java
CompletableTask
  .asyncOn(rootExec)
  .thenApplyAsync(..., exec1) 
  .thenApply(...) //A
  .handleAsync(...) //B
  .whenCompleteAsync(..., exec2)
  .thenRunAsync(); //C
  .;
```
How would you guess, what executor is used at points `A`, `B`, `C`? With my logic it's very simple: look at previous steps in the chain and see the most recently mentioned executor. So in `A` and `B` it will be `exec1` (and not `rootExec` !!!)  and point `C` it will be `exec2` (rahter than `exec1` or `rootExec`).

I hope you agree that this makes sense. :)

Regards,
Valery

**Comment by vsilaev** [comment] 2018-08-21 08:13
> For the second part, I assumed that CompletableTask.asyncOn(executor) would behave the same as .defaultAsyncOn(executor), but it doesn't.

In fact, they both do the same thing: specify what executor will be used implicitly in `*Async` operations when no explicit executor is passed

**Comment by chrisly42** [comment] 2018-08-21 11:38
The documentation should be clarified, especially what is regarded as a "default" and what calls override these defaults. Nevertheless: Specifying asyncOn() and .defaultAsyncOn() is **NOT** the same. Have you tried the provided test case? It will *hang* on p.get() with only asyncOn() as the handleAsync() is attempted to be executed on the shutdown executor (and throw an Exception and **THAT is the bug you need to be fixing**, regardless of the behavior of asyncOn()/defaultAsyncOn()), while when using

```
        Promise<Void> p = CompletableTask.asyncOn(executor)
                .defaultAsyncOn(executor)
```

The test will pass because the .handleAsync() without the explicit executor will revert back to the originally specified default executor in .defaultAsyncOn() that is NOT overwritten by the call to .thenApplyAsync().

**Comment by vsilaev** [comment] 2018-08-21 12:41
> The test will pass because the .handleAsync() without the explicit executor will revert back to the originally specified default executor in .defaultAsyncOn() that is NOT overwritten by the call to .thenApplyAsync().

Right. Because ExecutorBoundPromise (used by defaultAsyncOn) propagates own default executor further (wraps results of own thenApply / thenCombine / etc). 

> Have you tried the provided test case? It will hang on p.get() with only asyncOn() as the handleAsync() is attempted to be executed on the shutdown executor (and throw an Exception and THAT is the bug you need to be fixing, regardless of the behavior of asyncOn()/defaultAsyncOn())

Sure I tried your test. It throws synchronous exception on adding callbacks. Will provide a fix shortly.

**Comment by chrisly42** [comment] 2018-08-21 12:54
Thanks!

**Comment by vsilaev** [comment] 2018-08-21 14:07
Fix committed, please verify.
New version will be released shortly

**Comment by vsilaev** [comment] 2018-08-21 15:14
As a bonus pack -- CompletableTask.asyncOn now has additional parameter enforceDefaultAsync that let you create a chain with enforced default executor.

**Closed** 2018-08-22 09:32 UTC
